### ISSUE TITLE
Date read not display in right field

### ISSUE THREAD

**Issue by redg25** [jima80525/bobo#1]
In the edit pop up, the date read is displayed in the series field
![image](https://user-images.githubusercontent.com/52566911/138259036-0a51fe97-70f6-465f-909a-287d54f7c853.png)

**Comment by jima80525** [comment]
I have a fix for this.  Coming soon.

**Comment by jima80525** [comment]
This has been fixed.  I'm sure there are new bugs as this is still getting development :)

Thanks for the testing!
