### ISSUE TITLE
Error when clicking Cancel button

### ISSUE THREAD

**Issue by redg25** [jima80525/bobo#2]
If you click cancel on the edit pop up it closes the whole tool

**Comment by redg25** [comment]
The same behavior is happening with the Add button.

**Comment by jima80525** [comment]
I have a fix for this.  Will push it when I get the sorting-by-column part working.

**Comment by jima80525** [comment]
Sorry I didn't close this earlier.  Has been fixed for a while.  Thanks again for the input!
