### ISSUE TITLE
Instant update of json

### ISSUE THREAD

**Issue by redg25** [jima80525/bobo#3]
Books additions and edits are not displayed (json not updated) until you close and reopen the tool. Which means if I had one book for an author and want to add another straight away for the same author, it won't appear in the drop-down.

**Comment by jima80525** [comment]
Hmm.  I've got the other two figured out (stupid mistakes) but I can't reproduce this one.  If I add a new book with a new author and series, I see all three panes get updated when I hit enter.  

I'll push the quick fixes for the other two (thanks for reporting!) and will keep my eye on this one.  If you can repro, definitely take a look - both edit and add should call `update_info_and_ui()` if anything changed.

**Comment by redg25** [comment]
The issue is not the pane being updated, it is the author dropdwon when you want to add a new book straight away. Strangely it happens only from the second author. Try the following steps:
- Start from a blank db/json
- Add a book with Author A
- Add another book with Author B but notice that in the dropdown for author you can choose Author A
- Add another book and notice that in the dropdown for author you can only select author A.

Now if you close the app and reopen you will see all the authors in the dropdown.

**Comment by jima80525** [comment]
Thanks for fixing this one!
